Update to gym==0.26.x
coax-dev/coax pull request #28
Opened 2022-10-06 07:27 UTC by frederikschubert

This PR updates the requirements, wrappers and examples to the new API introduced by `gym==0.26.0`. 

Depends on https://github.com/coax-dev/coax/pull/27

2022-10-26 11:37 UTC, KristianHolsheimer requested changes

2022-10-26 11:37 UTC, KristianHolsheimer commented on requirements.dev.txt
> +gym[box2d]>=0.26.0
Dependency already covered in the main `requirements.txt`. Please remove.

2022-10-26 11:38 UTC, KristianHolsheimer commented
There seems to be a lot of overlap with #27. Do we need both PRs?

2022-10-26 11:43 UTC, KristianHolsheimer requested changes
Thanks so much for this!

Please could you update the examples in the docs as well?

For instance: [`doc/index.rst`](https://github.com/coax-dev/coax/blob/main/doc/index.rst)

2022-10-26 12:01 UTC, frederikschubert commented
> There seems to be a lot of overlap with #27. Do we need both PRs?

Yes, I basically wanted to show the changes separately. In the end, we can just merge https://github.com/coax-dev/coax/pull/29 as it contains all other changes as well.

2022-10-29 15:52 UTC, KristianHolsheimer approved these changes

2022-10-29 16:26 UTC, merged